# Name ,Contact,Class,Section,Contact number,Email

print('**************Student Basic Information **************\n\n')
print('[+] Name      :  Pranay Ashok Ramteke\n')
print('[+] Contact   :  pranayramteke613@gmail.com\n')
print('[+] Class     :  4th SEM \n')
print('[+] Section   :  B\n')
print('[+] Number    :  7378736964\n')

print('**************Student Bio Data **************\n\n')

print("\n--------------------------------------------------------")
print("Skills        : \n")
print("--------------------------------------------------------\n")
print("[01] C-Programming\n")
print("[02] C++ Programming\n")
print("[03] Python Programming\n")
print("[04] Flutter Devloplment\n")
print("[05] Social Engineering\n")
print("[06] Adobe Photoshop \n")
print("[07] Adobe Illustrator\n")
print("[08] Adobe XD\n")
print("[09] Figma Designing\n")
print("[10] Unreal C++ Devlopment\n")
print("[11] Git And Github\n")
print('[12] Bash Scripting\n')

print("\n--------------------------------------------------------------------------------------------------------------------")
print("PROJECTS AND DEVELOPMENTS     : \n")
print("---------------------------------------------------------------------------------------------------------------------\n")
print('[+] Project              |                     [+]Description                             |    [+]Duration   \n  ')
print("---------------------------------------------------------------------------------------------------------------------\n")
print('Social Media Poster      |              Content Designer for Brand Agencies               |       1-2 years \n')
print('Prototype Native App     |              Flutter Based app on Medcare industry             |       3-4 Days   \n')
print('Basic 3D shooter Game    |              Unreal C++ 3d Shooter Game with classes           |       1 month\n')
print('Key Logger               |              Devloped with Bash scripting to record keystroke  |       2 Weeks\n')
print('UI design of Mobile App  |              Developed with figma and Adobe XD                 |       1 Weeks\n')
print('Logo Design              |              Construction Company logo design                  |       3 Days\n')
print('Website Design           |              Personal CV website hosted on Guthub Pages        |       1 week \n')
